### ISSUE TITLE
Add Fake Ancient

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#11]
Add [ancient](https://github.com/faker-ruby/faker/blob/master/doc/default/ancient.md), which include: `God`, `Primordial`, `Titan`, and `Hero`.

**Comment by Caps-Looking** [comment]
Hey @CodyEngel can I take this one?

**Comment by CodyEngel** [comment]
Yeah @Caps-Looking feel free to pick this one up. I would err on the side of over-documenting this one though, `Ancient` isn't the most self-documenting name. Feel free to open a draft PR if you wanted early feedback around the documentation.
