### ISSUE TITLE
Add Fake App

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#12]
Add [app](https://github.com/faker-ruby/faker/blob/master/doc/default/app.md), which includes `name`, `version`, `author`, and `semanticVersion`. This should also include options to change the version's major/minor/patch values as well as being able to say if a library is early release or stable.

**Comment by CodyEngel** [comment]
If you have questions about implementing feel free to ask here. Also don't forget to ask if you can pick up the issue and I can assign it to you.

**Comment by Caps-Looking** [comment]
Hi @CodyEngel can I take this one?
Oh, and since we are implementing based on java-faker, the library doesn't support `semanticVersion` as in faker-ruby.
(https://github.com/DiUS/java-faker/blob/master/src/main/java/com/github/javafaker/App.java)
Should I implement all the other properties?

**Comment by CodyEngel** [comment]
Hey @Caps-Looking feel free to pick this one up. When it comes to the versioning I was thinking it'd make sense to just generate that on our own using [Random](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.random/-random/) to generate the major, minor, and patch.

Today we are using `java-faker` for a lot of the data generation but we will be breaking away from it shortly after the 1.0.0 release to start working on Kotlin Native support. Because of that I am okay with not using java faker if it doesn't support something that faker-ruby does and it's easy enough to implement.
