### ISSUE TITLE
Add Fake Artist

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#14]
Add [artist](https://github.com/faker-ruby/faker/blob/master/doc/default/artist.md) to `FakeContext`, which includes a `name`. Please see existing classes (`fakeAddress`, `fakeAvatar`, `fakeBook`, etc) for examples of how to implement & unit test.

**Comment by pedro-cze** [comment]
Hi @CodyEngel can I have this one? Cheers.

**Comment by CodyEngel** [comment]
Hey @pedro-cze it's all yours. Let me know if you have any questions 😄
