### ISSUE TITLE
Add Fake Color

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#17]
Add [color](https://github.com/faker-ruby/faker/blob/master/doc/default/color.md), currently this only needs to worry about `hexColor`, in the future we can add others like rgb, hsl, and hsla.

**Comment by RafaelPereiraSantos** [comment]
Hi @CodyEngel  I'm interested, may I try it?

**Comment by CodyEngel** [comment]
Hey @RafaelPereiraSantos, you're more than welcome to work on this. I haven't had a chance to put together contribution guidelines so my main asks would to be consistent with the other classes that are implemented.

Feel free to open a draft pull request if you would like early feedback on the work. Thank you so much for your interest in helping with this library 😄

**Comment by RafaelPereiraSantos** [comment]
@CodyEngel I will sure take a look in how you are organizing everything and come with something along these lines and
As soon I come with something I open a pr

**Comment by CodyEngel** [comment]
Sure thing @RafaelPereiraSantos -- you're assigned to the issue now.
