### ISSUE TITLE
Add Fake Company

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#18]
Add [company](https://github.com/faker-ruby/faker/blob/master/doc/default/company.md), which should include `bs`, `buzzword`, `catchPhrase`, `industry`, `logo`, name`, `profession`, `suffix`, and `url`.

**Comment by CodyEngel** [comment]
Going to assign this to @RafaelPereiraSantos, see #19 for more details.

**Comment by RafaelPereiraSantos** [comment]
hey @CodyEngel could you assign me this issue as we spoke in #19?

**Comment by CodyEngel** [comment]
@RafaelPereiraSantos assigned, thank you 😄
