### ISSUE TITLE
Add Fake Commerce

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#19]
Add [commerce](https://github.com/faker-ruby/faker/blob/master/doc/default/commerce.md), this should include `color`, `department`, `material`, `price`, `productName`, and `promotionCode`.

**Note:** does commerce make sense or would `product` be a better name for this?

**Comment by RafaelPereiraSantos** [comment]
Hi @CodyEngel may I take part in this?

Looking at the idea of "commerce" I agree that its seems in fact that it is a product, commerce should be other instance that contains this "product"

**Comment by CodyEngel** [comment]
@RafaelPereiraSantos would it make sense to have `commerce` be the combination of several other fakes? I think commerce could almost contain fake data from Fake Company (#18), Fake Address, and then Fake Product which could maybe be a list of products that the company sells?

**Comment by RafaelPereiraSantos** [comment]
@CodyEngel this sounds even better

After seeing this new idea I think ```commerce``` could be a kind of subtype of ```company``` (with products, addresses and so on) or an aggregation of these fake data you mentioned (fake: companies, products, addresses).

either way, I agree ```commerce``` should not be the product itself

what about that?

**Comment by CodyEngel** [comment]
Making commerce a sub-type of company makes sense to me @RafaelPereiraSantos. We'd want to leverage the information already present with company while also including the products and address.

**Comment by RafaelPereiraSantos** [comment]
Great! we could star by implementing a fake for  ```companies``` and them come back to this issue to create the subtype ``commerce``` with products and addresses, @CodyEngel 

If you agree I, would be gladly to start and take the issue #18, could you assign me ?

**Comment by CodyEngel** [comment]
@RafaelPereiraSantos yeah go ahead and pick up #18 -- I'm going to work on contributor roles over the next day or so. In the meantime if you could comment on #18 that should allow me to assign it to you.

**Comment by RafaelPereiraSantos** [comment]
hey @CodyEngel I saw that you merged my pr related to the issue #18 so I think we can start this one, what do you think? is there any point we need to discuss? other wise if you could assign me and I can start it.

**Comment by CodyEngel** [comment]
This is good to pick up @RafaelPereiraSantos, will go ahead and assign it to you. Thank you!
