### ISSUE TITLE
Add Fake Aviation

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#35]
Add a `FakeAviation` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val aviation = faker.aviation()
aviation.METAR()
aviation.aircraft()
aviation.airport()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by RafaelPereiraSantos** [comment]
Hi @CodyEngel, I would like to implement this one, could you assign me?

**Comment by CodyEngel** [comment]
Hey @RafaelPereiraSantos all yours.
