### ISSUE TITLE
Add Fake Beer

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#36]
Add a `FakeBeer` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val beer = faker.beer()
beer.hop()
beer.malt()
beer.name()
beer.style()
beer.yeast()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by mattkimmel** [comment]
I've got this one! 🎃

**Comment by mattkimmel** [comment]
Actually, I see that others have gone ahead and opened PRs without being assigned, so I'll go ahead and do the same. Enjoy!
