### ISSUE TITLE
Add Fake Cat

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#37]
Add a `FakeCat` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val cat = faker.cat()
cat.breed()
cat.name()
cat.registry()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by ewatch** [comment]
Hi @CodyEngel,

I would take care of this. :-)

**Comment by CodyEngel** [comment]
Awesome thank you @ewatch, merged in the changes.
