### ISSUE TITLE
Add Fake Cryptography

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#38]
Add a `FakeCryptography` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val crypto = faker.crypto()
crypto.md5()
crypto.sha1()
crypto.sha256()
crypto.sha512()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by RafaelPereiraSantos** [comment]
hi @CodyEngel, may I implement this one?

**Comment by CodyEngel** [comment]
Yup, all yours @RafaelPereiraSantos.
