### ISSUE TITLE
Add Fake Disease

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#40]
Add a `FakeDisease` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val disease = faker.medical()
disease.diseaseName()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by pedro-cze** [comment]
Hello @CodyEngel I will have a look at this one, if possible. Tahnks :)

**Comment by CodyEngel** [comment]
Hey @pedro-cze all yours!
