### ISSUE TITLE
Add Fake Dog

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#41]
Add a `FakeDog` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val dog = faker.dog()
dog.age()
dog.breed()
dog.coatLength()
dog.gender()
dog.memePhrase()
dog.name()
dog.size()
dog.sound()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by JacobKant** [comment]
Hi, i can help with this issue, assigned to me please

**Comment by CodyEngel** [comment]
Yup all yours @JacobKant.
