### ISSUE TITLE
Add Fake Educator

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#42]
Add a `FakeEducator` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val educator = faker.educator()
educator.campus()
educator.course()
educator.secondarySchool()
educator.university()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by pedro-cze** [comment]
Hello, @CodyEngel I will have a look at this one, if possible. Tahnks :)

**Comment by CodyEngel** [comment]
Hey @pedro-cze all yours!
