### ISSUE TITLE
Add Fake Job

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#43]
Add a `FakeJob` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val job = faker.job()
job.field()
job.keySkills()
job.position()
job.seniority()
job.title()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by Charis1331** [comment]
Hi @CodyEngel, can I be assigned to this?

**Comment by CodyEngel** [comment]
Yup all yours @Charis1331.
