### ISSUE TITLE
Add Fake SSN

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#45]
Add a `FakeSSN` instance to `FakeContext`. Please ensure that new properties are added in alphabetical order and well documented.

Here are points of reference from the `Faker` library:

```kotlin
val ssn = faker.idNumber()
ssn.valid()
ssn.invalid()
```

If you want to work on this please leave a comment so you can be assigned to this issue. Feel free to ask questions or open a draft PR if you are unsure on implementation details.

**Comment by Nowele** [comment]
I'd like to be assigned this issue
